
version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest  # Prebuilt image with pgvector
    container_name: knowledgebase-db
    environment:
      POSTGRES_DB: knowledgebase
      POSTGRES_USER: kbadmin
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # For initialization scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kbadmin"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: